version: 2 # CircleCI 2.0 を使用します
jobs: # 1回の実行の基本作業単位
  build: # Workflows を使用しない実行では、エントリポイントとして `build` ジョブが必要
    # ステップが実行されるディレクトリ
    working_directory: ~/djheroku
    docker: # Docker でステップを実行します
      # CircleCI Python イメージは https://hub.docker.com/r/cimg/python/ で入手できます
      - image: cimg/python:3.11
        environment: # プライマリコンテナの環境変数
          PIPENV_VENV_IN_PROJECT: true
          # DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps: # `build` ジョブを構成するステップ
      - checkout # ソースコードを作業ディレクトリにチェックアウトします
      - run:
          command: |
            python -m pip install --upgrade pip setuptools
            python -m pip install pipenv
            pipenv install --dev
            pipenv run static
      - run:
          command: |
            pipenv run test
